### ISSUE TITLE

        docs: feedback about experimental features
    

### ISSUE THREAD

**Issue by mrcego** [vitejs/docs-es#465]
New updates on head repo.
https://github.com/vitejs/vite/commit/378fbedfb964b126c3802e60c0886d5a9462e42b

**Comment by Franqsanz** [comment]
Hi, I have a question, the Spanish version does not contain these two [sections](https://github.com/vitejs/vite/commit/378fbedfb964b126c3802e60c0886d5a9462e42b#diff-383f1742681453dbe031bc12288890db21be111f60821901062fd1a28f286f07) in the documentation, specifically the part of `css.transformer` and `css.lightningcss`.

**Comment by mrcego** [comment]
Are you refering to https://es.vitejs.dev/config/shared-options.html#css-transformer?

**Comment by Franqsanz** [comment]
Yes, I got confused, I found it, sorry for the inconvenience!

**Comment by Franqsanz** [comment]
Hello, is there any rule for the translation for example in "Give Feedback" leave it as it is or for example "Dar Feedback"?

**Comment by mrcego** [comment]
I'm not sure what's you mean. If you want translating some section, do it always trying to get _the_ spanish context, unless there are "untranslatable" words like HMR.
