### ISSUE TITLE

        chore: deprecate splitVendorChunkPlugin
    

### ISSUE THREAD

**Issue by mrcego** [vitejs/docs-es#649]
New updates on head repo.
https://github.com/vitejs/vite/commit/45a06daac82524cf318a4dff7ae0b5f9cf67a0b2

**Comment by hibuna** [comment]
Please update the docs. They still reference the deprecated method.

https://v3.vitejs.dev/guide/build.html#chunking-strategy

**Comment by mrcego** [comment]
> Please update the docs. They still reference the deprecated method.
> 
> https://v3.vitejs.dev/guide/build.html#chunking-strategy

PR is welcome. Thanks.
